require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe PaintingsController do

  # This should return the minimal set of attributes required to create a valid
  # Painting. As you add validations to Painting, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all paintings as @paintings" do
      painting = Painting.create! valid_attributes
      get :index
      assigns(:paintings).should eq([painting])
    end
  end

  describe "GET show" do
    it "assigns the requested painting as @painting" do
      painting = Painting.create! valid_attributes
      get :show, :id => painting.id
      assigns(:painting).should eq(painting)
    end
  end

  describe "GET new" do
    it "assigns a new painting as @painting" do
      get :new
      assigns(:painting).should be_a_new(Painting)
    end
  end

  describe "GET edit" do
    it "assigns the requested painting as @painting" do
      painting = Painting.create! valid_attributes
      get :edit, :id => painting.id
      assigns(:painting).should eq(painting)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Painting" do
        expect {
          post :create, :painting => valid_attributes
        }.to change(Painting, :count).by(1)
      end

      it "assigns a newly created painting as @painting" do
        post :create, :painting => valid_attributes
        assigns(:painting).should be_a(Painting)
        assigns(:painting).should be_persisted
      end

      it "redirects to the created painting" do
        post :create, :painting => valid_attributes
        response.should redirect_to(Painting.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved painting as @painting" do
        # Trigger the behavior that occurs when invalid params are submitted
        Painting.any_instance.stub(:save).and_return(false)
        post :create, :painting => {}
        assigns(:painting).should be_a_new(Painting)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Painting.any_instance.stub(:save).and_return(false)
        post :create, :painting => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested painting" do
        painting = Painting.create! valid_attributes
        # Assuming there are no other paintings in the database, this
        # specifies that the Painting created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Painting.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => painting.id, :painting => {'these' => 'params'}
      end

      it "assigns the requested painting as @painting" do
        painting = Painting.create! valid_attributes
        put :update, :id => painting.id, :painting => valid_attributes
        assigns(:painting).should eq(painting)
      end

      it "redirects to the painting" do
        painting = Painting.create! valid_attributes
        put :update, :id => painting.id, :painting => valid_attributes
        response.should redirect_to(painting)
      end
    end

    describe "with invalid params" do
      it "assigns the painting as @painting" do
        painting = Painting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Painting.any_instance.stub(:save).and_return(false)
        put :update, :id => painting.id, :painting => {}
        assigns(:painting).should eq(painting)
      end

      it "re-renders the 'edit' template" do
        painting = Painting.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Painting.any_instance.stub(:save).and_return(false)
        put :update, :id => painting.id, :painting => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested painting" do
      painting = Painting.create! valid_attributes
      expect {
        delete :destroy, :id => painting.id
      }.to change(Painting, :count).by(-1)
    end

    it "redirects to the paintings list" do
      painting = Painting.create! valid_attributes
      delete :destroy, :id => painting.id
      response.should redirect_to(paintings_url)
    end
  end

end
